backend_payment/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from api import views


app_name = "api"

v1_router = DefaultRouter()
v1_router.register("payment", views.PaymentViewSet, basename='payment')
v1_router.register("payment_status", views.PaymentStatusView, basename='payment_status')
v1_router.register("payment_types", views.PaymentTypesView, basename='payment_types')

v1_router.register("withdraw", views.WithdrawViewSet, basename='withdraw')
v1_router.register("balance_changes", views.BalanceViewSet, basename='balance_changes')

# Для робота
v1_router.register("full_info", views.FullInfoView, basename='full_info')
v1_router.register("worker_payments", views.WorkerPaymentsView, basename='worker_payments')

urlpatterns = [
    path("", include(v1_router.urls)),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('payments_archive/', views.PaymentsArchive.as_view(), name='payments_archive'),

]

backend_payment/backend_payment/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

urlpatterns = [
    path('', include('payment.urls', namespace='payment')),
    path('', include('deposit.urls', namespace='deposit')),
    path('', include('balance_checker.urls', namespace='balance_checker')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('api/v1/', include('api.urls')),

    path('api/v1/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/v1/docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='docs'),
    path(
        'api/v1/redoc/',
        SpectacularRedocView.as_view(url_name='schema'),
        name='redoc'
    ),
]


handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

backend_payment/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import PasswordChangeDoneView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetCompleteView
from django.contrib.auth.views import PasswordResetDoneView
from django.contrib.auth.views import PasswordResetView
from django.urls import path, reverse_lazy
from . import views

app_name = 'users'

urlpatterns = [
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='login'),

    path('password_change/',
         PasswordChangeView.as_view(
             template_name='users/password_change_form.html',
             success_url='done/'),
         name='password_change'),

    path('password_change/done/',
         PasswordChangeDoneView.as_view(
             template_name='users/password_change_done.html'),
         name='password_change_done'),


    path('password_reset/',
         PasswordResetView.as_view(
                 template_name="users/password_reset_form.html",
                 email_template_name='users/password_reset_email.html',
                 success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset'),

    path('password_reset/done/',
         PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html',
             success_url=reverse_lazy("users:password_reset_complete")
         ),
         name='password_reset_confirm'),

    path('reset/done/',
         PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

# path('reset_password/', auth_views.PasswordResetView.as_view(
#     template_name="users/password_reset_form.html",
#     email_template_name='users/password_reset_email.html',
#     success_url=reverse_lazy('users:password_reset_done')
# ),

backend_payment/users/models.py
import datetime

from django.apps import apps
from django.conf import settings
from django.contrib import admin
from django.core.mail import send_mail
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin, Group
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.utils import timezone
from rest_framework.exceptions import ValidationError

from users.managers import UserManager


class WhiteListMerchant(models.Model):
    name = models.CharField('Наименование', unique=True)
    email = models.EmailField(unique=True)


class User(AbstractBaseUser, PermissionsMixin):
    username_validator = UnicodeUsernameValidator()

    USER = "user"
    STAFF = "staff"
    STAFF_PLUS = "staff+"
    ADMIN = "admin"
    MODERATOR = "editor"
    MERCHANT = "merchant"
    MERCHVIEWER = "merchviewer"
    ROLES = (
        (USER, "Пользователь"),
        (ADMIN, "Администратор"),
        (STAFF, "Оператор"),
        (STAFF_PLUS, "Оператор+"),
        (MODERATOR, "Корректировщик"),
        (MERCHANT, "Мерчант"),
        (MERCHVIEWER, "Помощник мерча")
    )

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    # id = models.UUIDField(primary_key=True, default=uuid4, editable=False, db_index=True)

    username = models.CharField(
        max_length=150,
        unique=True,
        validators=[username_validator],
    )

    email = models.EmailField(
        verbose_name="Email-адрес",
        null=False,
        blank=False
    )

    role = models.CharField(
        max_length=20,
        choices=ROLES,
        default=USER,
    )

    objects = UserManager()

    # Баланс AZN
    balance = models.DecimalField('Баланс AZN', max_digits=16, decimal_places=2, default=0)
    tax = models.FloatField('Комиссия card_2 AZN', default=9)
    tax_m10 = models.FloatField('Комиссия m10_to_m10 AZN', default=7)
    tax_card = models.FloatField('Комиссия card-to-card AZN', default=7)
    withdraw_tax = models.FloatField('Комиссия на вывод AZN', default=2)

    bdt_balance = models.DecimalField('Баланс BDT', max_digits=16, decimal_places=2, default=0)
    bdt_tax = models.FloatField('Комиссия bkash', default=9)
    bdt_withdraw_tax = models.FloatField('Комиссия на вывод BDT', default=2)

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        ordering = ('id',)

    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.id}. {self.username}'

    def get_short_name(self):
        return self.email

    def get_full_name(self):
        return self.username

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def group(self):
        user_groups = self.groups.values('name')
        group_list = []
        for group in user_groups:
            group_list.append(group.get('name'))
        return group_list

    def is_white(self):
        print('WhiteListMerchant:', WhiteListMerchant.objects.all())
        print(self.email)
        return WhiteListMerchant.objects.filter(email=self.email).exists()

    @admin.display(boolean=True, description='Видит уведомления?')
    def bad_warning(self):
        return self.profile.view_bad_warning


@receiver(pre_save, sender=User)
def pre_save_user(sender, instance: User, raw, using, update_fields, *args, **kwargs):
    if instance.is_white() and instance.id is None:
        instance.role = 'merchant'


@receiver(post_save, sender=User)
def after_save_user(sender, instance: User, created, raw, using, update_fields, *args, **kwargs):
    if created:
        instance.profile = Profile.objects.create(user=instance,
                                                  my_filter=[])
        instance.profile.save()
        if instance.is_white():
            instance.role = 'merchant'
            instance.is_active = 1
            instance.save()


class Profile(models.Model):
    user = models.OneToOneField(
        verbose_name="Пользователь", to=User, on_delete=models.CASCADE
    )

    first_name = models.CharField(
        verbose_name="Имя",
        max_length=30,
        null=True,
        blank=True
    )
    last_name = models.CharField(
        verbose_name="Фамилия",
        max_length=150,
        null=True,
        blank=True
    )

    my_filter = models.JSONField('Фильтр по получателю', default=list, blank=True)
    my_filter2 = models.JSONField('Фильтр по получателю2', default=list, blank=True)
    my_filter3 = models.JSONField('Фильтр по получателю3', default=list, blank=True)
    view_bad_warning = models.BooleanField(default=False)
    on_work = models.BooleanField(default=False)
    limit_to_work = models.IntegerField(default=0)
    last_id = models.IntegerField(default=0)
    is_bot = models.BooleanField(default=False)
    banks = models.ManyToManyField(to='payment.Bank', blank=True)
    payment_limit_per_minute = models.IntegerField('Лимит заявок в минуту. 0 - откл', default=0)
    bot_max_amount = models.PositiveIntegerField('Максимальная сумма бота. 0 - откл', default=0)

    def __str__(self):
        return f'{self.user.username}'

    class Meta:
        verbose_name = "Профиль пользователя"
        verbose_name_plural = "Профили пользователей"

    def limit_check(self) -> bool:
        Payment = apps.get_model('payment', 'Payment')
        limit = self.payment_limit_per_minute
        threshold = timezone.now() - datetime.timedelta(seconds=60)
        if limit:
            payments_count = Payment.objects.filter(merchant__owner__id=self.id, create_at__gte=threshold).count()
            if payments_count >= limit:
                return False
        return True


class SingletonModel(models.Model):
    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.__class__.objects.exclude(id=self.id).delete()
        super(SingletonModel, self).save(*args, **kwargs)

    @classmethod
    def load(cls):
        try:
            return cls.objects.get()
        except cls.DoesNotExist:
            return cls()


class SupportOptions(SingletonModel):
    operators_on_work = models.JSONField(verbose_name='Операторы на смене', default=dict)

    def __str__(self):
        return f'Options({self.operators_on_work})'

backend_payment/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'email')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
            if hasattr(self, "save_m2m"):
                self.save_m2m()
        return user

backend_payment/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/signup.html'

backend_payment/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

backend_payment/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-4 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% include 'includes/form_error.html' %}

          <form method="post"
            {% if action_url %}
              action="{% url 'users:login' %}"
            {% endif %}>
            {% csrf_token %}

            {% include 'includes/form_fields.html' %}

            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Войти
              </button>
              <a href="{% url 'users:password_reset' %}" class="btn btn-link">
                Забыли пароль?
              </a>
              <a href="{% url 'users:signup' %}" class="btn btn-link">
                Зарегистрироваться
              </a>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

backend_payment/templates/users/password_change_done.html
{% extends 'base.html' %}
{% block title %}Вы сменили пароль{% endblock %}
{% block content %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Пароль изменён
              </div>
              <div class="card-body"> 
                <p>Пароль изменён успешно</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
{% endblock %}

backend_payment/templates/users/password_change_form.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-4 p-5">
            <div class="card">
              <div class="card-header">
                Изменить пароль
              </div>
              <div class="card-body">

                {% include 'includes/form_error.html' %}

                <form method="post" action="{% url 'users:password_change' %}">
                  {% csrf_token %}
                  {% include 'includes/form_fields.html' %}

                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Изменить пароль
                    </button>
                  </div>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
{% endblock %}

backend_payment/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Восстановление пароля завершено
              </div>
              <div class="card-body">
                <p>Ваш пароль был сохранен. Используйте его для входа</p>
                <a href="{% url 'users:login' %}">войти</a>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
{% endblock %}

backend_payment/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
      <div class="container py-5">
        {% if validlink %}
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">

              {% if form.errors %}
                  {% for field in form %}
                    {% for error in field.errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <div class="card-header">
                Введите новый пароль
              </div>
              <div class="card-body">
                <form method="post">
                  {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль
                      <span class="required text-danger">*</span>
                    </label>
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                    <small id="id_new_password1-help" class="form-text text-muted">
                      <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                    </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля
                      <span class="required text-danger">*</span>
                    </label>
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Назначить новый пароль
                    </button>
                  </div>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
        {% else %}
        <!-- если использована неправильная ссылка -->
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Ошибка
              </div>
              <div class="card-body">
                <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
        {% endif %}
        <!-- конец если использована неправильная ссылка -->
      </div>
{% endblock %}

backend_payment/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Отправлено письмо
              </div>
              <div class="card-body">
                <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
{% endblock %}

backend_payment/templates/users/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your Account {{ user.email }},
click the link below:

{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

{% endautoescape %}

backend_payment/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-4 p-5">
            <div class="card">
              <div class="card-header">
                Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
              </div>
              <div class="card-body"> 
                <form method="post" >
                  <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
                  <div class="form-group row my-3 p-3">
                    <label for="id_email">
                      Адрес электронной почты
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Сбросить пароль
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>  
      </div>
{% endblock %}

backend_payment/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
            {% include 'includes/form_error.html' %}
            <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {% include 'includes/form_fields.html' %}

              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card-header-->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}