backend_payment/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from api import views


app_name = "api"

v1_router = DefaultRouter()
v1_router.register("payment", views.PaymentViewSet, basename='payment')
v1_router.register("payment_status", views.PaymentStatusView, basename='payment_status')
v1_router.register("payment_types", views.PaymentTypesView, basename='payment_types')

v1_router.register("withdraw", views.WithdrawViewSet, basename='withdraw')
v1_router.register("balance_changes", views.BalanceViewSet, basename='balance_changes')

# Для робота
v1_router.register("full_info", views.FullInfoView, basename='full_info')
v1_router.register("worker_payments", views.WorkerPaymentsView, basename='worker_payments')

urlpatterns = [
    path("", include(v1_router.urls)),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('payments_archive/', views.PaymentsArchive.as_view(), name='payments_archive'),

]

backend_payment/backend_payment/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

urlpatterns = [
    path('', include('payment.urls', namespace='payment')),
    path('', include('deposit.urls', namespace='deposit')),
    path('', include('balance_checker.urls', namespace='balance_checker')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('api/v1/', include('api.urls')),

    path('api/v1/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/v1/docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='docs'),
    path(
        'api/v1/redoc/',
        SpectacularRedocView.as_view(url_name='schema'),
        name='redoc'
    ),
]


handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

backend_payment/deposit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from deposit import views

app_name = 'deposit'

urlpatterns = [

    path('sms/', views.sms, name='sms'),
    path('create_copy_screen/', views.create_copy_screen, name='create_copy_screen'),
    # path('sms_forwarder/', views.sms_forwarder, name='sms_forwarder'),
    path('incomings/', views.IncomingListView.as_view(), name='incomings'),
    path('incomings/<int:pk>/', views.IncomingEdit.as_view(), name='incoming_edit'),
    path('trash/', views.IncomingTrashList.as_view(), name='trash'),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend_payment/deposit/forms.py
from django import forms

from deposit.models import Incoming
from payment.models import Payment


class IncomingForm(forms.ModelForm):

    comment = forms.CharField(widget=forms.Textarea, required=False)
    # confirmed_payment = forms.ModelChoiceField(queryset=Payment.objects.exclude(status__in=[-1, 9]), required=False)
    confirmed_payment = forms.CharField(required=False)

    def clean_confirmed_payment(self, *args):
        print(self.data)
        print(self.cleaned_data)
        print(self.instance)
        return self.data['confirmed_payment'].strip() or None

    class Meta:
        model = Incoming
        fields = ('confirmed_payment', 'comment',)

backend_payment/deposit/views.py
import datetime
import logging
import re
from http import HTTPStatus

import pytz
import structlog
from django.conf import settings
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, UpdateView
from rest_framework.decorators import api_view
from rest_framework.request import Request

from backend_payment.settings import TIME_ZONE
from core.global_func import send_message_tg
from deposit.filters import IncomingFilter
from deposit.forms import IncomingForm

from deposit.models import  Incoming, TrashIncoming

from deposit.text_response_func import response_sms1, response_sms2, response_sms3, response_sms4, response_sms5, \
    response_sms6, response_sms7, response_sms8, response_sms9, response_sms10, response_sms11, response_sms12, \
    response_sms13, response_sms14, response_sms15
from payment.models import Payment
from payment.permissions import StaffOnlyPerm

logger = structlog.getLogger(__name__)
TZ = pytz.timezone(TIME_ZONE)

patterns = {
    'sms1': r'^Imtina:(.*)\nKart:(.*)\nTarix:(.*)\nMercant:(.*)\nMebleg:(.*) .+\nBalans:(.*) ',
    'sms2': r'.*Mebleg:\s*(.*?) AZN.*\n*Kart:(.*)\n*Tarix:(.*)\n*Merchant:(.*)\n*Balans:(.*) .*',
    'sms3': r'^.+[medaxil|mexaric] (.+?) AZN (.*)(\d\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d).+Balance: (.+?) AZN.*',
    'sms4': r'^Amount:(.+?) AZN[\n]?.*\nCard:(.*)\nDate:(.*)\nMerchant:(.*)[\n]*Balance:(.*) .*',
    'sms5': r'.*Mebleg:(.+) AZN.*\n.*(\*\*\*.*)\nUnvan: (.*)\n(.*)\nBalans: (.*) AZN',
    'sms6': r'.*Mebleg:(.+) AZN.*\nHesaba medaxil: (.*)\nUnvan: (.*)\n(.*)\nBalans: (.*) AZN',
    'sms7': r'(.+) AZN.*\n(.+)\nBalans (.+) AZN\nKart:(.+)',
    'sms8': r'.*Mebleg: (.+) AZN.*Merchant: (.*)\sBalans: (.*) AZN',
    'sms9': r'(.*)\n(\d\d\d\d\*\*\d\d\d\d)\nMedaxil\n(.*) AZN\n(\d\d:\d\d \d\d\.\d\d.\d\d)\nBALANCE\n(.*)AZN',
    'sms10': r'(.*)\n(\d\d\d\d\*\*\d\d\d\d)\nMedaxil (.*) AZN\nBALANCE\n(.*) AZN\n(\d\d:\d\d \d\d\.\d\d.\d\d)',
    'sms11': r'Odenis\n(.*) AZN \n(.*\n.*)\n(\d\d\d\d\*\*\d\d\d\d).*\n(\d\d:\d\d \d\d\.\d\d.\d\d)\nBALANCE\n(.*) AZN',
    'sms12': r'(\d\d\.\d\d\.\d\d \d\d:\d\d)(.*)AZ Card: (.*) amount:(.*)AZN.*Balance:(.*)AZN',
    'sms13': r'[Odenis|Legv Edilme]: (.*) AZN\n(.*)\n(\d\d\d\d\*\*\d\d\d\d).*\n(\d\d:\d\d \d\d\.\d\d.\d\d)\nBALANCE\n(.*)',
    'sms14': r'^.+[medaxil|mexaric]: (.+?) AZN\n(.*)\n(\d\d:\d\d \d\d\.\d\d\.\d\d)\nBALANCE\n(.+?) AZN.*',
    'sms15': r'Medaxil C2C: (.+?) AZN\n(.*)\n(.*)\n(\d\d:\d\d \d\d\.\d\d\.\d\d)\nBALANCE\n(.+?) AZN.*'
}

response_func = {
    'sms1': response_sms1,
    'sms2': response_sms2,
    'sms3': response_sms3,
    'sms4': response_sms4,
    'sms5': response_sms5,
    'sms6': response_sms6,
    'sms7': response_sms7,
    'sms8': response_sms8,
    'sms9': response_sms9,
    'sms10': response_sms10,
    'sms11': response_sms11,
    'sms12': response_sms12,
    'sms13': response_sms13,
    'sms14': response_sms14,
    'sms15': response_sms15,
}


def save_incoming(responsed_pay) -> str:
    """
    Сохранение поступления Incoming в базу
    :param responsed_pay:
    :return: 'duplicate' / 'created' / None
    """
    save_status = None
    try:
        logger.info(f'Сохраняем в базу: {responsed_pay}')
        if responsed_pay.get('sms_type') in ['sms8', 'sms7']:
            # Шаблоны без времени
            logger.debug('Шаблоны без времени')
            threshold = datetime.datetime.now(tz=TZ) - datetime.timedelta(hours=12)
            is_duplicate = Incoming.objects.filter(
                sender=responsed_pay.get('sender'),
                pay=responsed_pay.get('pay'),
                balance=responsed_pay.get('balance'),
                register_date__gte=threshold
            ).exists()
        else:
            logger.debug('Шаблоны со временем')
            is_duplicate = Incoming.objects.filter(
                response_date=responsed_pay.get('response_date'),
                sender=responsed_pay.get('sender'),
                pay=responsed_pay.get('pay'),
                balance=responsed_pay.get('balance')
            ).exists()
        logger.debug(f'is_duplicate: {is_duplicate}')
        if is_duplicate:
            # logger.info('Дубликат sms:\n\n{text}')
            # msg = f'Дубликат sms:\n\n{text}'
            # send_message_tg(message=msg, chat_ids=settings.ALARM_IDS)
            save_status = 'duplicate'
        else:
            logger.debug(f'Создаем {responsed_pay}')
            created = Incoming.objects.create(**responsed_pay)
            logger.info(f'Создан: {created}')
            save_status = 'created'
        return save_status
    except Exception as err:
        logger.error(err)


def find_text_sms_type(text):
    text_sms_type = None
    for sms_type, pattern in patterns.items():
        search_result = re.findall(pattern, text)
        if search_result:
            logger.debug(f'Найдено: {sms_type}: {search_result}')
            text_sms_type = sms_type
            break
    return text_sms_type


def analyse_sms_text_and_save(text, params=None, *args, **kwargs):
    """
    Распознает текст и преобразует в dict responsed_pay, затем сохраняет в базу
    :param text:
    :param params:
    :param args:
    :param kwargs:
    :return: {'save_result': 'duplicate' / 'created' / 'trash', 'response_errors': response_errors}
    """
    if params is None:
        params = {}
    response_errors = []
    fields = ['response_date', 'recipient', 'sender', 'pay', 'balance',
              'transaction',
              'type']

    text_sms_type = find_text_sms_type(text)
    logger.debug(f'text_sms_type: {text_sms_type}')
    if text_sms_type:
        search_result = re.findall(patterns[text_sms_type], text)
        responsed_pay: dict = response_func[text_sms_type](fields, search_result[0])
        logger.debug(f'responsed_pay: {responsed_pay}')
        response_errors = responsed_pay.pop('errors')
        # Добавим получателя если его нет
        if not responsed_pay.get('recipient'):
            responsed_pay['recipient'] = params.get('imei')
        responsed_pay['worker'] = params.get('worker') or params.get('imei')
        # Обработка валидной смс
        logger.debug(f'responsed_pay added: {responsed_pay}')
        save_result = save_incoming(responsed_pay)

    else:
        logger.info(f'Неизвестный шаблон\n{text}')
        new_trash = TrashIncoming.objects.create(text=text, worker=params.get('worker') or params.get('imei'))
        logger.info(f'Добавлено в мусор: {new_trash}')
        save_result = 'trash'
    if not save_result:
        response_errors.append(f'Смс не сохранилась в базу!')
    return {'save_result': save_result, 'response_errors': response_errors}


@api_view(['POST'])
def create_copy_screen(request: Request):

    data = request.data
    logger.debug(data)
    Incoming.objects.get_or_create(**data)
    return HttpResponse(status=HTTPStatus.OK, content='ok')


@api_view(['POST'])
def sms(request: Request):
    """
    Прием sms
    {'id': ['b1899338-2314-400c-a4ff-a9ef3d890c79'], 'from': ['icard'], 'to': [''], 'message': ['Mebleg:+50.00 AZN '], 'res_sn': ['111'], 'imsi': ['400055555555555'], 'imei': ['123456789000000'], 'com': ['COM39'], 'simno': [''], 'sendstat': ['0']}>, host: asu-payme.com, user_agent: None, path: /sms/, forwarded: 91.201.000.000
    """
    errors = []
    text = ''
    try:
        host = request.META["HTTP_HOST"]  # получаем адрес сервера
        user_agent = request.META.get("HTTP_USER_AGENT")  # получаем данные бразера
        forwarded = request.META.get("HTTP_X_FORWARDED_FOR")
        path = request.path
        logger.info(f'request.data: {request.data},'
                     f' host: {host},'
                     f' user_agent: {user_agent},'
                     f' path: {path},'
                     f' forwarded: {forwarded}')

        post = request.POST
        text = post.get('message')
        sms_id = post.get('id')
        imei = post.get('imei')
        params = {'sms_id': sms_id, 'imei': imei}
        logger.info(f'Получена смс:\n{text}\nparams: {params}')
        result = analyse_sms_text_and_save(text, params)
        logger.debug(f'analyse result: {result}')
        save_result = result.get('save_result')
        logger.debug(f'save_result : {save_result}')
        errors = result.get('errors')

        if save_result == 'created':
            response = HttpResponse(status=HTTPStatus.CREATED, content=sms_id)
        elif save_result == 'duplicate':
            response = HttpResponse(status=HTTPStatus.OK, content=sms_id)
        else:
            # Мусор
            new_trash = TrashIncoming.objects.create(text=text, worker=params.get('worker') or params.get('imei'))
            send_message_tg(message=f'Добавлено в мусор:\n{text}', chat_ids=settings.ALARM_IDS)
            logger.info(f'Добавлено в мусор так как не удалось сохранить: {new_trash}')
            response = HttpResponse(status=HTTPStatus.OK, content=sms_id)
        return response

    except Exception as err:
        msg = f'Неизвестная ошибка при распознавании сообщения: {err}'
        logger.info(msg)
        logger.error(f'{msg}', exc_info=True)
        send_message_tg(message=msg, chat_ids=settings.ALARM_IDS)
        return HttpResponse(status=HTTPStatus.BAD_REQUEST)

    finally:
        if errors:
            msg = f'Ошибки при распознавании Payment sms:\n{errors}\n\n{text}'
            send_message_tg(message=msg, chat_ids=settings.ALARM_IDS)


# @api_view(['POST'])
# def sms_forwarder(request: Request):
#     """
#     Прием sms_forwarder
#     """
#     errors = []
#     text = ''
#     try:
#         host = request.META["HTTP_HOST"]  # получаем адрес сервера
#         user_agent = request.META.get("HTTP_USER_AGENT")  # получаем данные бразера
#         forwarded = request.META.get("HTTP_X_FORWARDED_FOR")
#         path = request.path

backend_payment/templates/deposit/incoming_edit.html
{% extends 'base.html' %}
{% block title %}Ручная корректировка{% endblock %}


{% block content %}
{% include 'includes/operator_menu.html' %}
  <div class="container">
    <div class="row justify-content-start ">
      <div class="col col-md-auto">
        <table class="table table-bordered table-sm" style="font-size: medium">
        <thead class="thead-dark align-content-center">
           <tr>
               <th>Поле</th>
               <th>Значение</th>
           </tr>
        </thead>
        <tbody>

            <tr>
                <td>id</td>
                <td>{{ incoming.id }}</td>
            </tr>
            <tr>
                <td>Поступил</td>
                <td>{{ incoming.register_date }}</td>
            </tr>
            <tr>
                <td>Время на чеке</td>
                <td>{{ incoming.response_date }}</td>
            </tr>
            <tr>
                <td>Получатель</td>
                <td>{{ incoming.recipient }}</td>
            </tr>
            <tr>
                <td>Отправитель</td>
                <td>{{ incoming.sender }}</td>
            </tr>
            <tr>
                <td>Платеж</td>
                <td>{{ incoming.pay }}</td>
            </tr>
            <tr>
                <td>Баланс</td>
                <td>{{ incoming.balance|default_if_none:"---" }}</td>
            </tr>
            <tr>
                <td>Источник</td>
                <td>{{ incoming.worker|default_if_none:"---" }}</td>
            </tr>
            <tr>
                <td>Транзакция</td>
                <td>{{ incoming.transaction|default_if_none:"---" }}</td>
            </tr>
            <tr>
                <td>Скрин</td>
                <td>{{ incoming.image }}</td>
            </tr>
            <tr>
                <td>Тип</td>
                <td>{{ incoming.type }}</td>
            </tr>
            <tr>
                <td>Подтверждено</td>
                <td>{{ incoming.birpay_confirm_time|default_if_none:"---"  }}</td>
            </tr>
            <tr>
                <td>Ручная корректировка</td>
                <td>{{ incoming.birpay_edit_time|default_if_none:"---"  }}</td>
            </tr>
            <tr>
                <td>Payment id</td>
                <td>{{ incoming.confirmed_payment.id|default_if_none:"---" }}</td>
            </tr>

        </tbody>
        </table>

      </div>

      <div class="col col-md-3">
          {% if incoming.image %}
        <img class="img" style="object-fit: cover; object-position: 0 0" src="/media/{{incoming.image}}" width="300" height="400">
          {% endif %}
      </div>
    </div>


    <div class="row justify-content-start  col-md-3">
        <div class="col">
        <br><b>Ручная корректировка:</b>
        <form method="POST">
            {% csrf_token %}
              {% include 'includes/form_fields.html' %}
            <input type="submit" value="Сохранить">
        </form>
        </div>
    </div>


  </div>


{% endblock %}

backend_payment/templates/deposit/incomings_list.html
{% extends 'base.html' %}
{% block title %}Список платежей{% endblock %}


{% block content %}
{% include 'includes/operator_menu.html' %}
<div class="container">

  {% with request.resolver_match.view_name as view_name %}

    <span class="row justify-content-start">
      <div class="col-6">
        <form method="GET">

  <div class="container">
      <form method="get">
        <div class="row">

            {% for field in filter.form  %}
                <div class="col-auto">
                <b>{{ field.label_tag }}</b><br>{{ field }}
                </div>
            {% endfor %}
            <div class="row">

            <button class="btn btn-info btn-light" type="submit">Фильтровать</button>
            </div>
        </div>
    </form>
  </div>

       </form>
      </div>
      <p id="last_id" hidden>{{ last_id }}</p>
      <p id="last_bad_id" hidden>{{ last_bad_id }}</p>
      <p id="filter" hidden>{{ filter }}</p>
      {% if view_name == 'deposit:incomings' or view_name == 'deposit:incomings_filter' %}
       <div class="col-3" role="alert" id="warnings" style="padding:  6px 0 6px 0; margin: 0 0 0 10px">
         <!-- Здесь будут отображаться уведомления -->
        </div>
      {% endif %}
    </span>


     {% include 'includes/paginator.html' %}
     <div class="container-fluid ">
     <table id="table" class="table table-bordered table-hover table-sm" style="font-size: 14px; line-height: 100%; padding: .1rem .1rem .1rem .1rem">
     <thead class="">
     <tr class="">
           <th>id</th>
           <th>T прих</th>
           <th>T на чеке</th>
           <th>Получатель</th>
           <th>Отправитель</th>
           <th>Pay</th>
           <th>Б</th>
           <th>transaction</th>
           <th>Payment_id</th>
       </tr>
     </thead>
     <tbody style="text-align: end" >
         {% for incoming in page_obj %}
         <tr title="{{incoming.comment|default_if_none:'' }}" id="pay{{ incoming.id }}"
                 {% if incoming.confirmed_payment %}
                 class="table-success"
                 {% endif %}>

            <td><a class="changelink" href="{% url 'deposit:incoming_edit' incoming.id %}">{{ incoming.id }}</a>
                {% if incoming.comment %}
                  *
                {% endif %}
            </td>
            <td>{{ incoming.register_date|date:"d.m H:i" }}</td>
            <td>{{ incoming.response_date|date:"d.m H:i" }}</td>
            <td>{{ incoming.recipient }}</td>

            <td>{{ incoming.sender }}</td>
            <td>{{ incoming.pay }}</td>
            <td>{{ incoming.balance|floatformat:0  }}</td>
                  {% load l10n %}
         {% localize off %}
            <td>{{ incoming.transaction }}</td>


            <td class="text-nowrap">
                <form action="{% url 'deposit:incomings' %}" method="post">
                                    {% csrf_token %}
                    <input type="text" style="margin-bottom: -0px; margin-top: -10px; font-size: 14px; height: 20px" minlength="0" maxlength="36" size="32"  value="{{incoming.confirmed_payment.id}}" name="incoming_id:{{ incoming.id }}">

                    {% if incoming.confirmed_payment %}
                      <button disabled style="margin-bottom: -10px; margin-top: -10px; height: 25px;font-size: small" type="submit" class="btn btn-success btn-sm">---</button>
                    {% else %}
                      <button style="margin-bottom: -00px; margin-top: -10px; height: 25px;font-size: small" type="submit" class="btn btn-warning btn-sm">Ok</button>
                    {% endif %}
                </form>
            </td>
         {% endlocalize %}

         </tr>
         {% endfor %}
     </tbody>
   </table>
   </div>
   {% include 'includes/paginator.html' %}
  {% endwith %}
</div>

{% endblock %}

backend_payment/templates/deposit/trash_list.html
{% extends 'base.html' %}
{% block title %}Домашняя страница{% endblock %}


{% block content %}
{% include 'includes/operator_menu.html' %}
    <div class="">
        {#      {% include 'includes/switcher2.html' %} #}
    </div>



    <div>
        <table id="table" class="table w-auto table-hover table-bordered" style="font-size: medium; line-height: 100%; padding: .1rem .1rem .1rem .1rem">

          <thead>
            <tr>
               <th>ID</th>
               <th>Дата</th>
               <th>Текст</th>
            </tr>
          </thead>

          <tbody>
              {% for obj in object_list %}
                <tr class="text-start">
                  <td>{{ obj.pk }}</td>
                  <td>{{ obj.register_date }}</td>
                  <td>{{ obj.text|linebreaks }}</td>
                </tr>
              {% endfor %}
          </tbody>

        </table>
    </div>

{% endblock %}

{% block javascript %}
    <script>
        setTimeout(function(){
            window.location.reload();
            }, 5000);
    </script>
{% endblock %}