backend_payment/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from api import views


app_name = "api"

v1_router = DefaultRouter()
v1_router.register("payment", views.PaymentViewSet, basename='payment')
v1_router.register("payment_status", views.PaymentStatusView, basename='payment_status')
v1_router.register("payment_types", views.PaymentTypesView, basename='payment_types')

v1_router.register("withdraw", views.WithdrawViewSet, basename='withdraw')
v1_router.register("balance_changes", views.BalanceViewSet, basename='balance_changes')

# Для робота
v1_router.register("full_info", views.FullInfoView, basename='full_info')
v1_router.register("worker_payments", views.WorkerPaymentsView, basename='worker_payments')

urlpatterns = [
    path("", include(v1_router.urls)),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('payments_archive/', views.PaymentsArchive.as_view(), name='payments_archive'),

]

backend_payment/backend_payment/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

urlpatterns = [
    path('', include('payment.urls', namespace='payment')),
    path('', include('deposit.urls', namespace='deposit')),
    path('', include('balance_checker.urls', namespace='balance_checker')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('api/v1/', include('api.urls')),

    path('api/v1/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/v1/docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='docs'),
    path(
        'api/v1/redoc/',
        SpectacularRedocView.as_view(url_name='schema'),
        name='redoc'
    ),
]


handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

backend_payment/deposit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from deposit import views

app_name = 'deposit'

urlpatterns = [

    path('sms/', views.sms, name='sms'),
    path('create_copy_screen/', views.create_copy_screen, name='create_copy_screen'),
    # path('sms_forwarder/', views.sms_forwarder, name='sms_forwarder'),
    path('incomings/', views.IncomingListView.as_view(), name='incomings'),
    path('incomings/<int:pk>/', views.IncomingEdit.as_view(), name='incoming_edit'),
    path('trash/', views.IncomingTrashList.as_view(), name='trash'),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend_payment/payment/urls.py
from django.conf.urls.static import static
from django.urls import path, include

from backend_payment import settings
from . import views

app_name = 'payment'

urlpatterns = [

    path('support_options/', views.SupportOptionsView.as_view(), name='support_options'),
    path('show_log/<str:pk>/', views.show_log, name='show_log'),

    path('', views.menu, name='menu'),
    path('invoice/', views.invoice, name='pay_check'),
    path('pay_to_card_create/', views.pay_to_card_create, name='pay_to_card_create'),  # card-to-card
    path('pay_to_m10_create/', views.pay_to_m10_create, name='pay_to_m10_create'),  # card_2
    path('pay_to_m10_wait_work/', views.pay_to_m10_wait_work, name='pay_to_m10_wait_work'),
    path('pay_to_m10_sms_input/', views.pay_to_m10_sms_input, name='pay_to_m10_sms_input'),
    path('m10_to_m10_create/', views.m10_to_m10_create, name='m10_to_m10_create'),  # m10_to_m10
    path('pay_result/<str:pk>/', views.PayResultView.as_view(), name='pay_result'),
    path('payments/', views.PaymentListView.as_view(), name='payment_list'),
    path('payments_stats/', views.PaymentStatListView.as_view(), name='payments_stats'),
    path('payments_summary/', views.PaymentListSummaryView.as_view(), name='payments_summary'),
    path('payments_count/', views.PaymentListCount.as_view(), name='payment_count'),
    path('payments/<str:pk>/', views.PaymentEdit.as_view(), name='payment_edit'),
    path('payments_input/<str:pk>/', views.PaymentInput.as_view(), name='payment_input'),
    path('withdraws/', views.WithdrawListView.as_view(), name='withdraw_list'),
    path('withdraws/<str:pk>/', views.WithdrawEdit.as_view(), name='withdraw_edit'),
    path('balance_history/', views.BalanceHistoryListView.as_view(), name='balance_history_list'),
    # path('merch_stat/<int:pk>', views.MerchStatView.as_view(), name='merch_stats'),
    path('merchowners/<int:pk>/', views.MerchOwnerDetail.as_view(), name='merch_owner_detail'),
    path('merchowners/', views.MerchOwnerList.as_view(), name='merch_owner_list'),
    path('on_work/', views.on_work, name='on_work'),

    path('wait_requisite/<str:pk>/', views.wait_requisite, name='wait_requisite'),
    path('payment_type_not_worked/', views.payment_type_not_worked, name='payment_type_not_worked'),


    path('invoice_test_start/', views.invoice_test, name='invoice_test'),
    path('get_bank/<str:bin_num>/', views.get_bank, name='get_bank'),

    # Merh
    path('create_merchant/', views.MerchantCreate.as_view(), name='create_merchant'),
    path('merchant/<str:pk>/', views.MerchantDetail.as_view(), name='merchant_detail'),  # Shop
    path('merchant_delete/<str:pk>/', views.MerchantDelete.as_view(), name='merchant_delete'),
    path('merchant_orders/', views.MerchantOrders.as_view(), name='merchant_orders'),
    path('merchant_test_webhook/', views.merchant_test_webhook, name='merchant_test_webhook'),
    # path('export_payments/', views.export_payments, name='export_payments'),
    path('balance/', views.BalanceListView.as_view(), name='balance_list'),

    path('receive_webhook/', views.WebhookReceive.as_view(), name='receive_webhook'),
    path('repeat_webhook/<str:pk>', views.PaymentWebhookRepeat.as_view(), name='repeat_webhook'),
    path('withdraw_repeat_webhook/<str:pk>', views.WithdrawWebhookRepeat.as_view(), name='withdraw_repeat_webhook'),

    # path('test/', views.Test.as_view(), name='test'),

    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend_payment/payment/models.py
import datetime
import json
import uuid
from decimal import Decimal
from enum import Enum

import structlog
from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.exceptions import ObjectDoesNotExist

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models, transaction
from django.db.models import F, Sum, Model, Q
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.utils import timezone
from django.contrib.postgres.fields import ArrayField
from django_currentuser.middleware import get_current_user, get_current_authenticated_user

from core.global_func import hash_gen, TZ
from payment.task import send_payment_webhook, send_withdraw_webhook, send_message_tg_task, send_payment_to_work_oper


logger = structlog.get_logger(__name__)

User = get_user_model()


class Currency(Enum):
    AZN = {
        "code": "AZN",
        "title": "Azerbaijani Manat",
        "title_rus": "Azerbaijani Manat",
        "symbol": "₼",
        "native": "ман.",
        "exp": 2
    }
    BDT = {
        "code": "BDT",
        "title": "Bangladeshi taka",
        "title_rus": "Бангладешская така",
        "symbol": "৳",
        "native": "Tk",
        "exp": 2
    }

    def __init__(self, vals):
        self.code = vals['code']
        self.title = vals['title']
        self.symbol = vals['symbol']
        self.native = vals['native']
        self.exp = vals['exp']

    def __str__(self):
        return f'{self.symbol}'


CURRENCY_CHOICES = [(currency.code, f'{currency.code} - {currency.symbol}') for currency in Currency]


class Merchant(models.Model):
    is_new = models.BooleanField(verbose_name='Новенький', default=1)
    name = models.CharField('Название', max_length=100)
    owner = models.ForeignKey(to=User, related_name='merchants', on_delete=models.CASCADE)
    host = models.URLField('Адрес для отправки вэбхук payment')
    host_withdraw = models.URLField('Адрес для отправки вэбхук withdraw.', default='')
    secret = models.CharField('Your secret key', max_length=1000)
    check_balance = models.BooleanField('Принимать заявку на вывод только при достаточном балансе:',
                                        default=False)
    white_ip = models.CharField('Принимать только с этих адресов (через ";" Например : "127.0.0.1;127.0.0.2")',
                                null=True, blank=True, default='')
    dump_webhook_data = models.BooleanField(default=False)
    # Endpoints
    pay_success_endpoint = models.URLField('Default Url for redirect user back to your site', null=True, blank=True)
    merch_viewers = ArrayField(
            models.CharField(max_length=50, blank=True),
            size=5, default=list, blank=True
        )

    def stat(self):
        confirmed_payments = self.payments.filter(status=9)
        count = confirmed_payments.count()
        result = confirmed_payments.aggregate(total_sum=Sum('confirmed_amount'))
        return {
            'count': count,
            'total_sum': result['total_sum']}

    def __str__(self):
        return f'Shop {self.id}. ({self.owner}) {self.name}'

    def ip_list(self):
        ips = []
        if self.white_ip:
            raw_ips = self.white_ip.split(';')
            for ip in raw_ips:
                ip = ''.join([char for char in ip if char.isdigit() or char in ['.']])
                ips.append(ip)
        return ips

    class Meta:
        ordering = ('id',)


@receiver(post_save, sender=Merchant)
def after_save_shop(sender, instance: Merchant, created, raw, using, update_fields, *args, **kwargs):
    logger.debug(f'after_save_shop {created}')
    if created:
        text = (f'Создан новый магазин id {instance.id}:\n'
                f'{instance.name}\n'
                f'{instance.owner}')
        send_message_tg_task.delay(text, settings.ADMIN_IDS)


class BalanceChange(models.Model):
    create_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='balance_history')
    amount = models.DecimalField(max_digits=16, decimal_places=2, verbose_name='Изменение баланса')
    currency_code = models.CharField(choices=CURRENCY_CHOICES, default='AZN')
    current_balance = models.DecimalField(max_digits=16, decimal_places=2, verbose_name='Текущий баланс AZN', null=True)
    comment = models.CharField(null=True, blank=True)

    class Meta:
        ordering = ('-create_at',)

    def __str__(self):
        return f'{self.id}. {self.create_at} {self.comment} ({"-" if self.amount < 0 else "+"}{self.amount} {self.currency_code}) ---> {self.current_balance} {self.currency_code}'


class CreditCard(models.Model):
    card_number = models.CharField('Номер карты', max_length=19)
    owner_name = models.CharField('Имя владельца', max_length=100, null=True, blank=True)
    cvv = models.CharField(max_length=4, null=True, blank=True)
    card_type = models.CharField('Система карты', max_length=100)
    card_bank = models.CharField('Название банка', max_length=50, default='Bank')
    expired_month = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(12)])
    expired_year = models.IntegerField(validators=[MinValueValidator(20), MaxValueValidator(40)])
    status = models.CharField('Статус карты',
                              default='not_active',
                              choices=[
                                  ('active', 'Активна'),
                                  ('not_active', 'Не активна'),
                                  ('blocked', 'Заблокирована')
                              ])

    def __repr__(self):
        string = f'{self.__class__.__name__} ({self.id}){self.card_number}'
        return string

    def __str__(self):
        string = f'СС {self.id}. {self.card_number}'
        return string


PAY_TYPE = (
        ('card-to-card', 'card-to-card'),
        ('card_2', 'card_2'),
        ('m10_to_m10', 'm10_to_m10'),
    )


class PayRequisite(models.Model):

    pay_type = models.CharField('Тип платежа', choices=PAY_TYPE)
    card = models.OneToOneField(to=CreditCard, on_delete=models.CASCADE, null=True, blank=True)
    is_active = models.BooleanField(default=False)
    info = models.CharField('Инструкция для пользователя', null=True, blank=True)
    info2 = models.CharField('Инфо 2', null=True, blank=True)
    method_info = models.CharField('Описание метода', null=True, blank=True)
    min_amount = models.IntegerField(default=0)
    max_amount = models.IntegerField(default=10000)

    def __repr__(self):
        string = f'{self.__class__.__name__}({self.id})'
        return string

    def __str__(self):
        string = f'{self.pay_type} {self.id}. {self.card}'
        return string


class Withdraw(models.Model):
    WITHDRAW_STATUS = (
        (-1, '-1. Decline'),
        (0, '0. Created'),
        (9, '9. Confirmed'),
    )

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.cached_status = self.status

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, max_length=36, db_index=True,
                          unique=True, )
    merchant = models.ForeignKey('Merchant', verbose_name='Shop', on_delete=models.CASCADE, related_name='withdraws')
    withdraw_id = models.CharField(max_length=64, db_index=True)
    amount = models.IntegerField('Сумма заявки', validators=[MinValueValidator(30), MaxValueValidator(10000)])
    currency_code = models.CharField(choices=CURRENCY_CHOICES, default='AZN')
    payload = models.JSONField(default=str, blank=True, null=True)
    create_at = models.DateTimeField('Время добавления в базу', auto_now_add=True)
    status = models.IntegerField('Статус заявки',
                                 default=0,
                                 choices=WITHDRAW_STATUS)
    comission = models.DecimalField('Комиссия', max_digits=16, decimal_places=2, null=True, blank=True)
    change_time = models.DateTimeField('Время изменения в базе', auto_now=True)
    card_data = models.JSONField('Данные карты для выплаты', default=str, null=True, blank=True)
    target_phone = models.CharField('Телефон для выплаты на m10', max_length=20, null=True, blank=True)
    confirmed_time = models.DateTimeField('Время подтверждения', null=True, blank=True)
    confirmed_user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    balance_before = models.DecimalField('Баланс на момент заявки', max_digits=18, decimal_places=2, default=0)
    balance_after = models.DecimalField('Баланс после выплаты', max_digits=18, decimal_places=2, default=0)
    comment = models.CharField('Комментарий', max_length=1000, null=True, blank=True)
    response_status_code = models.IntegerField(null=True, blank=True)

    class Meta:
        ordering = ('-create_at',)

    def status_str(self):
        for status_num, status_str in self.WITHDRAW_STATUS:
            if status_num == self.status:
                return status_str

    def balance(self):
        return self.merchant.owner.balance

    def webhook_data(self):
        if self.status == 9:
            data = {
                "id": str(self.id),
                "withdraw_id": self.withdraw_id,
                "amount": self.amount,
                "currency_code": self.currency_code,
                "create_at": self.create_at.isoformat(),
                "status": self.status,
                "confirmed_time": self.confirmed_time.isoformat(),
            }
        elif self.status == -1:
            data = {
                'withdraw_id': self.withdraw_id,
                'id': str(self.id),
                'status': -1,
            }
        else:
            data = {}
        return data


class Payment(models.Model):
    PAYMENT_STATUS = (
        (-1, '-1. Decline'),
        (0, '0. Created'),
        (3, '3. CardData input.'),

backend_payment/templates/payment/bash.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div class="container">
        <div class="row">
        <form method="POST" enctype="multipart/form-data" style="height:100%; padding: 1px; margin: 1px">
          {% csrf_token %}
            {{form.as_p}}

            <button id="confirm_btn" class="btn btn-success btn btn-block" type="submit">Ok</button>
        </form>
        </div>
        </div>
</body>
</html>

backend_payment/templates/payment/credit_card.html
{% load static %}
<style>
    .big {
        color: #e8912a;
        font-size: xx-large;
        font-weight: bold;
    }

    .bank {
        font-weight: bold;
    }

    .back {
        background-color: black;
        color: white;
        border-top-right-radius: 50px
    }

    .number {
        font-weight: bold;
        letter-spacing: 2px;
    }
</style>

<div class="card" style="margin: 10px 30px 10px 30px; border-radius: 20px">
    <div class="back card-header" style="border-top-left-radius: 20px; border-top-right-radius: 20px">
        <div class="row justify-content-center align-items-center text-center" >
            <div class="col-6">
                Ödəniş məbləği:
            </div>

            <div class="col-6 big">
         {{ payment.amount }} ₼
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="row bank">
            <span class="title">{{ payment.pay_requisite.card.card_bank }}</span>
        </div>
                <div class="row">
            <span class="title">CARD NUMBER</span>
        </div>
        <div class="row">
            <span id="card_num" class="number">
                {{ payment.pay_requisite.card.card_number|slice:":4" }}
                {{ payment.pay_requisite.card.card_number|slice:"4:8" }}
                {{ payment.pay_requisite.card.card_number|slice:"8:12" }}
                {{ payment.pay_requisite.card.card_number|slice:"12:" }}
            <img onclick="CopyToClipboard('card_num')" style="opacity: 1; background-color: #198653" class="img-thumbnail" width="32" height="32" src="{% static '/img/copy.png' %}"></span>
        </div>


        <div class="row">
            <span class="exp">Data {{ payment.pay_requisite.card.expired_month }}/{{ payment.pay_requisite.card.expired_year }}</span>
        </div>
        <div class="row">
            <span class="name">{{ payment.pay_requisite.card.owner_name|default_if_none:'' }}</span>
        </div>

    </div>
</div>

<script>
  function CopyToClipboard(containerid) {
  if (document.selection) {
    var range = document.body.createTextRange();
    range.moveToElementText(document.getElementById(containerid));
    range.select().createTextRange();
    document.execCommand("copy");
  } else if (window.getSelection) {
    var range = document.createRange();
    range.selectNode(document.getElementById(containerid));
    window.getSelection().addRange(range);
    document.execCommand("copy");
    alert("Номер скопирован")
  }
}
</script>

backend_payment/templates/payment/invoice_m10_sms.html
{% extends 'base.html' %}
{% block title %}Оплата
{% endblock %}
{% block content %}


<div class="container margin: auto" style="max-width: 500px;">
  <div class="card"  style="background: #efefef">

    <div class="card-header">
      <div class="row">
          <div class="col-4" style="padding: 0 0 0 0">
          </div>
          <div class="col-4 d-flex justify-content-center"  style="padding: 0 0 0 0; margin: 0 0 0 0px">
              <img class="mx-auto d-flex justify-content-center" src="/static/img/AsuPay125.png" height="125" width="125">
          </div>
          <div class="col-4" style="padding: 0 0 0 0; margin: 0 0 0 0">
          </div>
      </div>
      <div class="row">
        <div class="col-9 mx-auto" style="display: flex; align-items: center;">
        </div>
      </div>
    </div>

    <div class="card-body justify-content-center align-items-center text-center">
      <form method="POST" enctype="multipart/form-data">
      <div id="time_is_up" style="display: none">Vaxt bitdi, zəhmət olmasa səhifəyə qayıdın və yeni sorğu yaradın</div>  {# Таймер истёк, вернитесь пожалуйста  на сайт и создайте новую заявку #}
      {% csrf_token %}
      {% if not phone_script.step_2_required %} {# Если смс не требуется #}
        <div class="row">
          Ödənişi təstiqləmək üçün Leobank mobil tədbiqində Sizə bildiriş gələcək.
             Zəhmət olmasa, Leobank mobil tədbiqinə keçid edin və köçürməni təstiq edin {# .(Вам в приложении Леобанка придет уведомление для подтверждения  платежа. Перейдите пожалуйста  в приложении  лео банка и подтвердите перевод в приложении) #}
        </div>
        <input  type="submit" value="Продолжить" class="btn btn-success">
      {% else %}  {# Если смс требуется #}
        <div id="send_sms_btn" style="display: block" class="row justify-content-center align-items-center text-center">
          <div class="row">Zəhmət olmasa telefonunuza gələn SMS kodunu daxil edin və SMS Göndər düyməsini basın!{# пожалуйста  смс код который пришёл на ваш телефон введите #}
          </div>
          <div class="row">
          {% include 'includes/form_error.html' %}
          <div  class="col-6">
            <input class="icon" type="text" name="sms_code" placeholder="SMS kodu" minlength="4" maxlength="6" id="id_sms_code">
          </div>
          <div class="col-6">
            <input id="sms" type="submit" value="SMS Göndər" class="btn btn-success placeicon"> {# отправить код   смс #}
          </div>
        </div>
      </div>
      {% endif %}

      </form>


    </div>
    <div class="card-footer">
      <div class="row">
      <div class="col-9 d-flex justify-content-center align-items-center">
                        {% if payment.status == 0 %}
                        Əməliyyat üçün qalan vaxt: {# время на совершенние оплаты #}
                        {% elif payment.status == 4 %}
                        SMS üçün qalan vaxt: {# время для ввода смс #}
                        {% endif %}
      </div>
      <div class="col-1">
           {% include 'includes/timer_circle.html' %}
      </div>
      </div>
    </div>
  </div>
</div>

<script>

var status = {{ payment.status }};

function getStatus() {
fetch('https://asu-payme.com/api/v1/payment_status/{{payment.id}}/', {
    method: 'GET',
    headers: {'Content-Type': 'application/json'},
}).then(response => response.json())
       .then(result => { if (status.toString() !== result['status'].toString()) {
           location.reload()
       } else {
           if (!['9', '-1'].includes(status.toString()))  {
               setTimeout(() => {getStatus()}, 3000);
           }
       }
       })
}
setTimeout(() => { getStatus() }, 3000);
</script>

{% endblock %}

backend_payment/templates/payment/menu.html
{% extends 'base.html' %}
{% block title %}Меню{% endblock %}

{% block content %}
{% include 'includes/header.html' %}


    <div class="container">
        <div class="row">
            <div class="col-4">
            Баланс: {{ request.user.balance }} ₼
            </div>
            {% if user.is_superuser or user.role == 'staff+' %}
            <a class="" href="{% url 'payment:merch_owner_list' %}">Список мерчей</a>
            <a class="" href="{% url 'payment:balance_history_list' %}">Изменения баланса мерчей</a><br>
            <a class="" href="{% url 'payment:payments_stats' %}">Статистика</a>
            {% endif %}
           {% if user.is_staff %}
               <a class="" href="{% url 'payment:support_options' %}">Операторы на смене</a>
               <div>
                   <a class="" href="{% url 'payment:payment_list' %}">Заявки payment</a>
               </div>
                <a class="" href="{% url 'payment:withdraw_list' %}">Заявки на Выводы withdraw</a>
            <hr>
             <a class="" href="{% url 'deposit:incomings' %}">Пополнения смс incomings</a>
             <a class="" href="{% url 'deposit:trash' %}">Смс мусор incomings </a>
           {% endif %}
           {% if user.role == 'merchant' or  user.role == 'merchviewer' %}
               <div><a class="" href="{% url 'payment:merchant_orders' %}">merchant_orders</a> </div>
            <a class="" href="{% url 'payment:withdraw_list' %}">Заявки на Выводы withdraw</a>
           {% endif %}
             <a class="" href="{% url 'payment:balance_list' %}">Изменения баланса</a><br>
        </div>
    </div>

    {% if user.role == 'merchant' %}
        <div class="container">
            <div class="row">
                    <a class="" href="{% url 'payment:create_merchant' %}">Создать Merchant</a><br>
            </div>
        </div>

        <div class="container flex">

         {% for merchant in merchants %}
            <div class="card">
                <div class="card-header">
                        {{ merchant.id }}. {{ merchant.name }}
                </div>
                <div class="card-body">
                    <div class="row">
                        <b>Статистика:</b><br>
                        Confirmed count: {{ merchant.payments.count }}<br>
                        Total confirmed amount: {{merchant.stat.total_sum}} ₼
                    </div>
                </div>
                <div class="card-footer">
                   <div class="row">
                      <div class="col-3">
                        <a class="" href="{% url 'payment:merchant_detail' merchant.id %}">Редактировать</a>
                      </div>
                      {% if merchant.payments.count == 0 %}
                      <div class="col-3">
                        <a class="" href="{% url 'payment:merchant_delete' merchant.id %}">Удалить (Только пустые)</a>
                      </div>
                      {% endif %}
                    </div>
                </div>
            </div>
         {% endfor %}
       </div>



    {% endif %}
{% endblock %}

backend_payment/templates/payment/merch_stat.html
{% extends 'base.html' %}
{% block title %}Подробно о мерче{% endblock %}


{% block content %}
{% include 'includes/operator_menu.html' %}
  <div class="container">
      <div class="row">
      <div class="col-md-auto">
              <form method="get">
        {{ filter.form }}
                   <button type="submit">Фильтровать</button>
        </form>
      </div>

  </div>
    <div class="row justify-content-start ">
      <div class="col col-md-auto">
        <table class="table table-bordered table-sm" style="font-size: medium">
        <thead class="thead-dark align-content-center">
           <tr>
               <th>Поле</th>
               <th>Значение</th>
           </tr>
        </thead>
        <tbody>

            <tr>
                <td>name</td>
                <td>{{ merch_user.username }}</td>
            </tr>
            <tr>
                <td>current_balance</td>
                <td>{{ balance }}</td>
            </tr>

            <tr>
                <td>total_payment_amount</td>
                <td>{{stat.total_amount}}</td>
            </tr>
            <tr>
                <td>total_payment_count</td>
                <td>{{stat.count_total}}</td>
            </tr>

                    <tr>
                <td>confirmed_payment_count</td>
                <td>{{stat.count_confirmed}}</td>
            </tr>
            <tr>
                <td>confirmed_amount</td>
                <td>{{stat.confirmed_amount}}</td>
            </tr>

                    <tr>
                <td>declined_payment_count</td>
                <td>{{stat.count_declined}}</td>
            </tr>

<!--            <tr>-->
<!--                <td>operator_avg_time</td>-->
<!--                <td>{{stat.operator_avg_time}}</td>-->
<!--            </tr>-->
        <tr>
                <td>conversion</td>
                <td>{{stat.conversion}}</td>
            </tr>

        </tbody>
        </table>

      </div>


    </div>

     <table id="table" class="table table-bordered table-hover table-sm" style="font-size: 14px; line-height: 100%; padding: .1rem .1rem .1rem .1rem">
              <thead class="">
                   </thead>

{% for payment in filter.qs|slice:":100" %}
         <tr>
             <td><a href="{% url 'payment:payment_edit' payment.id %}">{{payment}}</a></td>
<td>{{payment.create_at|date:"d.m H:i"}}</td>
<td>{{payment.amount}}</td>
<td>{{payment.status_str}}</td>
             <td>{{payment.oper_time}}</td>
{% endfor %}
         </tr>

{% endblock %}

backend_payment/templates/payment/merchant_confirm_delete.html
{%extends 'base.html'%}

{%block content%}
<div class="center">
	<form method="post" class="card">
		{% csrf_token %}
		<h2>Delete Merchant</h2>
		<p>Are you sure that you want to delete "{{merchant}}"?</p>
		<p class="form-buttons">
			<input type="submit" class="btn btn-primary" value="Delete">
			<a href="{% url 'payment:menu'%}" class="btn btn-outline">Cancel</a>
		</p>
	</form>
</div>

{%endblock content%}

backend_payment/templates/payment/payment_type_not_worked.html
В настоящий момент платежи по данным реквизитам не принимаются