backend_payment/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from api import views


app_name = "api"

v1_router = DefaultRouter()
v1_router.register("payment", views.PaymentViewSet, basename='payment')
v1_router.register("payment_status", views.PaymentStatusView, basename='payment_status')
v1_router.register("payment_types", views.PaymentTypesView, basename='payment_types')

v1_router.register("withdraw", views.WithdrawViewSet, basename='withdraw')
v1_router.register("balance_changes", views.BalanceViewSet, basename='balance_changes')

# Для робота
v1_router.register("full_info", views.FullInfoView, basename='full_info')
v1_router.register("worker_payments", views.WorkerPaymentsView, basename='worker_payments')

urlpatterns = [
    path("", include(v1_router.urls)),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('payments_archive/', views.PaymentsArchive.as_view(), name='payments_archive'),

]

backend_payment/backend_payment/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

urlpatterns = [
    path('', include('payment.urls', namespace='payment')),
    path('', include('deposit.urls', namespace='deposit')),
    path('', include('balance_checker.urls', namespace='balance_checker')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('api/v1/', include('api.urls')),

    path('api/v1/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/v1/docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='docs'),
    path(
        'api/v1/redoc/',
        SpectacularRedocView.as_view(url_name='schema'),
        name='redoc'
    ),
]


handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

backend_payment/payment/urls.py
from django.conf.urls.static import static
from django.urls import path, include

from backend_payment import settings
from . import views

app_name = 'payment'

urlpatterns = [

    path('support_options/', views.SupportOptionsView.as_view(), name='support_options'),
    path('show_log/<str:pk>/', views.show_log, name='show_log'),

    path('', views.menu, name='menu'),
    path('invoice/', views.invoice, name='pay_check'),
    path('pay_to_card_create/', views.pay_to_card_create, name='pay_to_card_create'),  # card-to-card
    path('pay_to_m10_create/', views.pay_to_m10_create, name='pay_to_m10_create'),  # card_2
    path('pay_to_m10_wait_work/', views.pay_to_m10_wait_work, name='pay_to_m10_wait_work'),
    path('pay_to_m10_sms_input/', views.pay_to_m10_sms_input, name='pay_to_m10_sms_input'),
    path('m10_to_m10_create/', views.m10_to_m10_create, name='m10_to_m10_create'),  # m10_to_m10
    path('pay_result/<str:pk>/', views.PayResultView.as_view(), name='pay_result'),
    path('payments/', views.PaymentListView.as_view(), name='payment_list'),
    path('payments_stats/', views.PaymentStatListView.as_view(), name='payments_stats'),
    path('payments_summary/', views.PaymentListSummaryView.as_view(), name='payments_summary'),
    path('payments_count/', views.PaymentListCount.as_view(), name='payment_count'),
    path('payments/<str:pk>/', views.PaymentEdit.as_view(), name='payment_edit'),
    path('payments_input/<str:pk>/', views.PaymentInput.as_view(), name='payment_input'),
    path('withdraws/', views.WithdrawListView.as_view(), name='withdraw_list'),
    path('withdraws/<str:pk>/', views.WithdrawEdit.as_view(), name='withdraw_edit'),
    path('balance_history/', views.BalanceHistoryListView.as_view(), name='balance_history_list'),
    # path('merch_stat/<int:pk>', views.MerchStatView.as_view(), name='merch_stats'),
    path('merchowners/<int:pk>/', views.MerchOwnerDetail.as_view(), name='merch_owner_detail'),
    path('merchowners/', views.MerchOwnerList.as_view(), name='merch_owner_list'),
    path('on_work/', views.on_work, name='on_work'),

    path('wait_requisite/<str:pk>/', views.wait_requisite, name='wait_requisite'),
    path('payment_type_not_worked/', views.payment_type_not_worked, name='payment_type_not_worked'),


    path('invoice_test_start/', views.invoice_test, name='invoice_test'),
    path('get_bank/<str:bin_num>/', views.get_bank, name='get_bank'),

    # Merh
    path('create_merchant/', views.MerchantCreate.as_view(), name='create_merchant'),
    path('merchant/<str:pk>/', views.MerchantDetail.as_view(), name='merchant_detail'),  # Shop
    path('merchant_delete/<str:pk>/', views.MerchantDelete.as_view(), name='merchant_delete'),
    path('merchant_orders/', views.MerchantOrders.as_view(), name='merchant_orders'),
    path('merchant_test_webhook/', views.merchant_test_webhook, name='merchant_test_webhook'),
    # path('export_payments/', views.export_payments, name='export_payments'),
    path('balance/', views.BalanceListView.as_view(), name='balance_list'),

    path('receive_webhook/', views.WebhookReceive.as_view(), name='receive_webhook'),
    path('repeat_webhook/<str:pk>', views.PaymentWebhookRepeat.as_view(), name='repeat_webhook'),
    path('withdraw_repeat_webhook/<str:pk>', views.WithdrawWebhookRepeat.as_view(), name='withdraw_repeat_webhook'),

    # path('test/', views.Test.as_view(), name='test'),

    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend_payment/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import PasswordChangeDoneView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetCompleteView
from django.contrib.auth.views import PasswordResetDoneView
from django.contrib.auth.views import PasswordResetView
from django.urls import path, reverse_lazy
from . import views

app_name = 'users'

urlpatterns = [
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='login'),

    path('password_change/',
         PasswordChangeView.as_view(
             template_name='users/password_change_form.html',
             success_url='done/'),
         name='password_change'),

    path('password_change/done/',
         PasswordChangeDoneView.as_view(
             template_name='users/password_change_done.html'),
         name='password_change_done'),


    path('password_reset/',
         PasswordResetView.as_view(
                 template_name="users/password_reset_form.html",
                 email_template_name='users/password_reset_email.html',
                 success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset'),

    path('password_reset/done/',
         PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html',
             success_url=reverse_lazy("users:password_reset_complete")
         ),
         name='password_reset_confirm'),

    path('reset/done/',
         PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

# path('reset_password/', auth_views.PasswordResetView.as_view(
#     template_name="users/password_reset_form.html",
#     email_template_name='users/password_reset_email.html',
#     success_url=reverse_lazy('users:password_reset_done')
# ),

backend_payment/templates/includes/form_error.html
{% if form.errors %}
    {% for field in form %}
      {% for error in field.errors %}
        <div class="alert alert-danger">
          {{ error|escape }}
        </div>
      {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
{% endif %}

backend_payment/templates/includes/form_fields.html
{% for field in form %}
  <div class="form-group row my-3"
    {% if field.field.required %}
      aria-required="true"
    {% else %}
      aria-required="false"
    {% endif %}>
    {% for error in field.errors %}
        <div class="alert alert-danger">
          {{ error|escape }}
        </div>
    {% endfor %}
    {% for error in form.non_field_errors %}
      <div class="alert alert-danger">
          {{ error|escape }}
      </div>
    {% endfor %}
    {% if not field.is_hidden %}
      <label for="{{ field.id_for_label }}">
      {{ field.label }}
      {% if field.field.required %}
        <span class="required text-danger">*</span>
      {% endif %}
    {% endif %}
    </label>
    {{ field }}
    <div>
      {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
          {{ field.help_text|safe }}
        </small>
      {% endif %}
    </div>
  </div>
{% endfor %}

backend_payment/templates/includes/header.html
    <div class="container">
        <div class="row">
            <div class="col-12">
              {% include 'includes/user_menu.html' %}
            </div>
        </div>
    </div>

backend_payment/templates/includes/operator_menu.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
{% with request.resolver_match.app_name as app_name %}
<div class="container">
  <nav class="navbar navbar-expand-md bg-body-tertiary">
  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
          <a class="nav-link" href="{% url 'payment:menu' %}">Меню</a>
          </li>
      </ul>

    {% if user.is_superuser %}
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

    </div>
    {% endif %}

      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
          <a class="nav-link" href="{% url 'admin:index' %}">Админка</a>
          </li>
      </ul>

      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Пользователь: {{ user.username }}</a>


          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
          </li>

        {% else %}
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'users:login' %}
                active
              {% endif %}" href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light
              {% if view_name  == 'users:signup' %}
                active
              {% endif %}
              "href="{% url 'users:signup' %}">Регистрация</a>
          </li>
        {% endif %}
      </ul>


  </nav>
    {% if user.is_authenticated %}

    {% endif %}



</div>
{% endwith %}
{% endwith %}

backend_payment/templates/includes/paginator.html
{% load l10n %}
{% localize off %}
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="">
  <ul class="pagination">
    {% load spurl %}
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="{% spurl query=request.GET set_query='page=1'%}"><<</a></li>
      <li class="page-item">
        <a class="page-link" href="{% spurl query=request.GET set_query='page={{ page_obj.previous_page_number }}'%}">
          <
        </a>
      </li>

        {% else %}

          <li class="page-item">
        <a class="page-link" href="">
          --
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="">
          -
        </a>
      </li>

    {% endif %}

    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>

        {% elif i >= page_obj.number|add:-5 and i <= page_obj.number|add:5  %}
          <li class="page-item">
            <a class="page-link" href="{% spurl query=request.GET set_query='page={{ i }}'%}">{{ i }}</a>
          </li>

        {% elif i == page_obj.number|add:-10 or i == page_obj.number|add:10  %}
          <li class="page-item">
            <a class="page-link" href="{% spurl query=request.GET set_query='page={{ i }}'%}">{{ i }}</a>
        {% elif i == page_obj.number|add:-50 or i == page_obj.number|add:50  %}
          <li class="page-item">
            <a class="page-link" href="{% spurl query=request.GET set_query='page={{ i }}'%}">{{ i }}</a>
          </li>
        {% elif i == page_obj.number|add:-100 or i == page_obj.number|add:100  %}
          <li class="page-item">
            <a class="page-link" href="{% spurl query=request.GET set_query='page={{ i }}'%}">{{ i }}</a>
          </li>
        {% elif i == page_obj.number|add:-500 or i == page_obj.number|add:500  %}
          <li class="page-item">
            <a class="page-link" href="{% spurl query=request.GET set_query='page={{ i }}'%}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">

        <a class="page-link" href="{% spurl query=request.GET set_query='page={{ page_obj.next_page_number }}'%}">
          >
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="{% spurl query=request.GET set_query='page={{ page_obj.paginator.num_pages }}'%}">
          >>
        </a>
      </li>
    {% else %}

          <li class="page-item">
        <a class="page-link" href="">
          -
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="">
          --
        </a>
      </li>

    {% endif %}
  </ul>
</nav>
{% endif %}
{% endlocalize %}

backend_payment/templates/includes/refresh_3sec.html
<script>
    setTimeout(function(){
        window.location.reload();
        }, 3000);
</script>

backend_payment/templates/includes/result_timer.html
<style>
    {#body {#}
    {#    font-family: Arial, sans-serif;#}
    {#}#}

    h1 {
        color: #333;
    }

    #timer {
        background-color: #dadada;
        text-align: center;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        padding: 20px;
        margin: 20px auto;
        max-width: 300px;
    }

    #countdown {
        font-size: 24px;
        font-weight: bold;
        color: #e44d26;
    }

    #event {
        {#font-size: 34px;#}
        font-weight: bold;
        color: #221d1c;
    }
</style>

    <div id="timer">
{#        <h3 id="event">{{ data.name }}</h3>#}
        <h4>Təstiqləməyə qədər vaxt:</h4> {# Time Remaining #}
        <div id="countdown">
            {{ data.hours|stringformat:"02d" }} : {{ data.minutes|stringformat:"02d" }} : {{ data.seconds|stringformat:"02d" }}
{#            {{ data.minutes|stringformat:"02d" }} : {{ data.seconds|stringformat:"02d" }}#}
        </div>
    </div>

<script>
    // Function to update the countdown timer
    function updateTimer() {
        var hours = parseInt(document.getElementById('countdown').textContent.split(':')[0]);
        var minutes = parseInt(document.getElementById('countdown').textContent.split(':')[1]);
        var seconds = parseInt(document.getElementById('countdown').textContent.split(':')[2]);

        if (seconds > 0) {
            seconds--;
        } else {
            if (minutes > 0) {
                minutes--;
                seconds = 59;
            } else {
                if (hours > 0) {
                    hours--;
                    minutes = 59;
                    seconds = 59;
                } else {
                    // Timer has reached zero, you can handle this case as needed
                    var element1 = document.getElementById('support_info');
                    element1.style.display = "block";

                }
            }
        }

        // Update the timer display
        document.getElementById('countdown').textContent =

            (hours < 10 ? '0' : '') + hours + ' : ' +
            (minutes < 10 ? '0' : '') + minutes + ' : ' +
            (seconds < 10 ? '0' : '') + seconds;
    }

    // Update the timer every second
    {#window.onload = updateTimer#}
    setInterval(updateTimer, 1000);
</script>

backend_payment/templates/includes/timer.html
<style>
    {#body {#}
    {#    font-family: Arial, sans-serif;#}
    {#}#}

    h1 {
        color: #333;
    }

    #timer {
        background-color: #dadada;
        text-align: center;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        padding: 10px;
        margin: 10px auto;
        max-width: 300px;
    }

    #countdown {
        font-size: 24px;
        font-weight: bold;
        color: #e44d26;
    }

    #event {
        {#font-size: 34px;#}
        font-weight: bold;
        color: #221d1c;
    }
</style>

    <div id="timer">
        <h3 id="event">{{ data.name }}</h3>
<!--        <h4>Time Remaining:</h4>-->
        <div id="countdown">
            {{ data.hours|stringformat:"02d" }} : {{ data.minutes|stringformat:"02d" }} : {{ data.seconds|stringformat:"02d" }}
        </div>
    </div>

<script>
    // Function to update the countdown timer
    function updateTimer() {
        var hours = parseInt(document.getElementById('countdown').textContent.split(':')[0]);
        var minutes = parseInt(document.getElementById('countdown').textContent.split(':')[1]);
        var seconds = parseInt(document.getElementById('countdown').textContent.split(':')[2]);

        if (seconds > 0) {
            seconds--;
        } else {
            if (minutes > 0) {
                minutes--;
                seconds = 59;
            } else {
                if (hours > 0) {
                    hours--;
                    minutes = 59;
                    seconds = 59;
                } else {
                    // Timer has reached zero, you can handle this case as needed
                    var element1 = document.getElementById('confirm_btn');
                    var element2 = document.getElementById('time_exp_info1');
                    var element3 = document.getElementById('pay_input');

                    element1.style.display = "none";
                    element2.style.display = "block";
                    element3.style.display = "none";
                }
            }
        }

        // Update the timer display
        document.getElementById('countdown').textContent =
            (hours < 10 ? '0' : '') + hours + ' : ' +
            (minutes < 10 ? '0' : '') + minutes + ' : ' +
            (seconds < 10 ? '0' : '') + seconds;
    }

    // Update the timer every second
    {#window.onload = updateTimer#}
    setInterval(updateTimer, 1000);
</script>

backend_payment/templates/includes/timer_circle.html
<style>

    body {
  font-family: sans-serif;
  display: grid;
  height: 100vh;
  place-items: center;
}

.base-timer {
  position: relative;
  width: 50px;
  height: 50px;
}

.base-timer__svg {
  transform: scaleX(-1);
}

.base-timer__circle {
  fill: none;
  stroke: none;
}

.base-timer__path-elapsed {
  stroke-width: 7px;
  stroke: grey;
}

.base-timer__path-remaining {
  stroke-width: 7px;
  stroke-linecap: round;
  transform: rotate(90deg);
  transform-origin: center;
  transition: 1s linear all;
  fill-rule: nonzero;
  stroke: currentColor;
}

.base-timer__path-remaining.green {
  color: rgb(65, 184, 131);
}

.base-timer__path-remaining.orange {
  color: orange;
}

.base-timer__path-remaining.red {
  color: red;
}

.base-timer__label {
  position: absolute;
  width: 50px;
  height: 50px;
  top: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 16px;
}

</style>

<div id="app"></div>

<script>



const FULL_DASH_ARRAY = 283;
const WARNING_THRESHOLD = 10;
const ALERT_THRESHOLD = 5;

const COLOR_CODES = {
  info: {
    color: "green"
  },
  warning: {
    color: "orange",
    threshold: WARNING_THRESHOLD
  },
  alert: {
    color: "red",
    threshold: ALERT_THRESHOLD
  }
};

const TIME_LIMIT = {{ data.limit}};
let timePassed = {{ data.time_passed}};
let timeLeft = {{data.total_seconds}};
let timerInterval = null;
let remainingPathColor = COLOR_CODES.info.color;

document.getElementById("app").innerHTML = `
<div class="base-timer">
  <svg class="base-timer__svg" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
    <g class="base-timer__circle">
      <circle class="base-timer__path-elapsed" cx="50" cy="50" r="45"></circle>
      <path
        id="base-timer-path-remaining"
        stroke-dasharray="283"
        class="base-timer__path-remaining ${remainingPathColor}"
        d="
          M 50, 50
          m -45, 0
          a 45,45 0 1,0 90,0
          a 45,45 0 1,0 -90,0
        "
      ></path>
    </g>
  </svg>
  <span id="base-timer-label" class="base-timer__label">${formatTime(
    timeLeft
  )}</span>
</div>
`;

startTimer();

function onTimesUp() {
  clearInterval(timerInterval);
  var element1 = document.getElementById('send_sms_btn');
  var element2 = document.getElementById('send_cc_data');
  var element3 = document.getElementById('time_is_up');
  element1.style.display = "none";
  element3.style.display = "block";
  element2.style.display = "none";
}

function startTimer() {
  timerInterval = setInterval(() => {
    timePassed = timePassed += 1;
    timeLeft = TIME_LIMIT - timePassed + 0;
    document.getElementById("base-timer-label").innerHTML = formatTime(
      timeLeft + 1
    );
    setCircleDasharray();
    setRemainingPathColor(timeLeft);

    if (timeLeft < 0) {
      onTimesUp();

    }
  }, 1000);
}

function formatTime(time) {
  const minutes = Math.floor(time / 60);
  let seconds = time % 60;

  if (seconds < 10) {
    seconds = `0${seconds}`;
  }

  return `${minutes}:${seconds}`;
}

function setRemainingPathColor(timeLeft) {
  const { alert, warning, info } = COLOR_CODES;
  if (timeLeft <= alert.threshold) {
    document
      .getElementById("base-timer-path-remaining")
      .classList.remove(warning.color);
    document
      .getElementById("base-timer-path-remaining")
      .classList.add(alert.color);
  } else if (timeLeft <= warning.threshold) {
    document
      .getElementById("base-timer-path-remaining")
      .classList.remove(info.color);
    document
      .getElementById("base-timer-path-remaining")
      .classList.add(warning.color);
  }
}

function calculateTimeFraction() {
  const rawTimeFraction = timeLeft / TIME_LIMIT;
  return rawTimeFraction - (1 / TIME_LIMIT) * (1 - rawTimeFraction);
}

function setCircleDasharray() {
  const circleDasharray = `${(
    calculateTimeFraction() * FULL_DASH_ARRAY
  ).toFixed(0)} 283`;
  document
    .getElementById("base-timer-path-remaining")
    .setAttribute("stroke-dasharray", circleDasharray);
}


</script>

backend_payment/templates/includes/timer_horizontal.html
<style>

    h1 {
        color: #333;
    }

    #timer {
        background-color: white;
        text-align: center;
        border-radius: 5px;
        {#box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);#}
        padding: 10px;
        margin: 10px auto;
        max-width: 80%;
    }

    #countdown {
        font-size: xx-large;
        font-weight: bold;
        color: #e8912a;
    }

    #event {
        font-size: medium;

        color: #221d1c;
    }
</style>

    <div class="row justify-content-center align-items-center text-center" id="timer">
{#        <div id="event" class="col-7">{{ data.name }}</div> #}
        <div class="col-12" id="countdown">
            {{ data.minutes|stringformat:"02d" }} : {{ data.seconds|stringformat:"02d" }}
        </div>
    </div>

<script>
    // Function to update the countdown timer
    function updateTimer() {
        var minutes = parseInt(document.getElementById('countdown').textContent.split(':')[0]);
        var seconds = parseInt(document.getElementById('countdown').textContent.split(':')[1]);

        if (seconds > 0) {
            seconds--;
        } else {
            if (minutes > 0) {
                minutes--;
                seconds = 59;
            } else  {
                    // Timer has reached zero, you can handle this case as needed
                    var element1 = document.getElementById('confirm_btn');
                    var element2 = document.getElementById('time_exp_info1');
                    var element3 = document.getElementById('pay_input');

                    element1.style.display = "none";
                    element2.style.display = "block";
                    element3.style.display = "none";

            }
        }

        // Update the timer display
        document.getElementById('countdown').textContent =

            (minutes < 10 ? '0' : '') + minutes + ' : ' +
            (seconds < 10 ? '0' : '') + seconds;
    }

    // Update the timer every second
    {#window.onload = updateTimer#}
    setInterval(updateTimer, 1000);
</script>

backend_payment/templates/includes/user_menu.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
{% with request.resolver_match.app_name as app_name %}
<div class="container">
  <nav class="navbar navbar-expand-md bg-body-tertiary">

      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if user.is_superuser %}
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <a class="nav-link" href="{% url 'admin:index' %}">Админка</a>
            </div>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'payment:menu' %}">Меню</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="">Пользователь: {{ user.username }} ({{ user.role }})</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
          </li>
        {% else %}
          <li class="nav-item">
              <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'users:signup' %}">Регистрация</a>
          </li>
        {% endif %}
      </ul>
  </nav>
</div>
{% endwith %}
{% endwith %}